- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Stop existing container
      shell: docker stop poc-app || true

    - name: Remove existing container
      shell: docker rm poc-app || true

    - name: Build Docker image
      shell: docker build -t poc-app .

    - name: Run Docker container
      shell: docker run -d -p 80:3000 --name poc-app poc-app

